version: "3.7"

services:
  db:
    image: postgres
    container_name: fastfeet_pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fastfeet_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: fastfeet
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
